# Generated by Django 5.1.1 on 2024-09-04 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boost',
            name='boost_type',
            field=models.CharField(choices=[('double', 'Удвоить сегодняшние очки'), ('freeze', 'Заморозить стрик'), ('extra_points', 'Увеличить колличество очков в день')], max_length=50),
        ),
    ]
