# Generated by Django 5.1.1 on 2024-09-04 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levelprize',
            name='received',
            field=models.DateField(null=True),
        ),
    ]
